const data = {
  products: [
    {
      _id: "1",
      image: "/images/2009 Honda CRV drier.jpg",
      type: "Ac/drier",
      make: "Honda",
      model: "CRV",
      year: "2009",
      qty: 50,
      price: 12000,
    },
    {
      _id: "2",
      image: "/images/2009 Toyota RAV4 drier.jpg",
      type: "Ac/drier",
      make: "Toyota",
      model: "RAV4",
      year: "2009",
      qty: 20,
      price: 11000,
    },
    {
      _id: "3",
      image: "/images/2010 Ford Escape drier.jpg",
      type: "Ac/drier",
      make: "Ford",
      model: "Escape",
      year: "2010",
      qty: 80,
      price: 14000,
    },
    {
      _id: "4",
      image: "/images/2010 Ford Focus drier.jpg",
      type: "Ac/drier",
      make: "Ford",
      model: "Focus",
      year: "2010",
      qty: 30,
      price: 19000,
    },
    {
      _id: "5",
      image: "/images/2010 Mazda 3  drier.jpg",
      type: "Ac/drier",
      make: "Mazda",
      model: "Mazda 3",
      year: "2010",
      qty: 51,
      price: 11000,
    },
    {
      _id: "6",
      image: "/images/2011 Audi A5 cabin.jpg",
      type: "Cabin Filter",
      make: "Audi",
      model: "A5",
      year: "2011",
      qty: 13,
      price: 1200,
    },
    {
      _id: "7",
      image: "/images/2011 Audi A5 comp.jpg",
      type: "Compressor",
      make: "Audi",
      model: "A5",
      year: "2011",
      qty: 45,
      price: 85000,
    },
    {
      _id: "8",
      image: "/images/2011 Audi A5 drier.jpg",
      type: "Ac/drier",
      make: "Audi",
      model: "A5",
      year: "2011",
      qty: 23,
      price: 2500,
    },
    {
      _id: "9",
      image: "/images/2011 Audi A5 valve.jpg",
      type: "Exapansion Valve",
      make: "Audi",
      model: "A5",
      year: "2011",
      qty: 100,
      price: 1200,
    },
    {
      _id: "10",
      image: "/images/2011 Honda Pilot drier.jpg",
      type: "Ac/drier",
      make: "Honda",
      model: "Pilot",
      year: "2011",
      qty: 98,
      price: 1000,
    },
    {
      _id: "11",
      image: "/images/2014 Honda CRV cabin.jpg",
      type: "Cabin Filter",
      make: "Honda",
      model: "CRV",
      year: "2014",
      qty: 53,
      price: 1300,
    },
    {
      _id: "12",
      image: "/images/2014 Honda CRV comp.jpg",
      type: "Compressor",
      make: "Honda",
      model: "CRV",
      year: "2014",
      qty: 10,
      price: 120000,
    },
    {
      _id: "13",
      image: "/images/2014 Honda CRV valve.jpg",
      type: "Expansion valve",
      make: "Honda",
      model: "CRV",
      year: "2014",
      qty: 120,
      price: 12000,
    },
    {
      _id: "14",
      image: "/images/2014 Land Rover LR4 cabin.jpg",
      type: "Cabin Filter",
      make: "Land Rover",
      model: "LR4",
      year: "2014",
      qty: 50,
      price: 1100,
    },
    {
      _id: "15",
      image: "/images/2014 Land Rover LR4 valve.jpg",
      type: "Expansion valve",
      make: "Land Rover",
      model: "LR4",
      year: "2014",
      qty: 70,
      price: 12000,
    },
    {
      _id: "16",
      image: "/images/2016 BMW X5  valve.jpg",
      type: "Expansion valve",
      make: "BMW",
      model: "X5",
      year: "2016",
      qty: 40,
      price: 17000,
    },
    {
      _id: "17",
      image: "/images/2016 BMW X5 cabin.jpg",
      type: "Cabin Filter",
      make: "BMW",
      model: "X5",
      year: "2016",
      qty: 10,
      price: 1300,
    },
    {
      _id: "18",
      image: "/images/2016 BMW X5 comp.jpg",
      type: "Compressor",
      make: "BMW",
      model: "X5",
      year: "2016",
      qty: 5,
      price: 250000,
    },
    {
      _id: "19",
      image: "/images/2017 Honda Accord cabin.jpg",
      type: "Cabin filter",
      make: "Honda",
      model: "Accord",
      year: "2017",
      qty: 140,
      price: 1500,
    },
    {
      _id: "20",
      image: "/images/2017 Honda Accord comp.jpg",
      type: "Compressor",
      make: "Honda",
      model: "Accord",
      year: "2017",
      qty: 12,
      price: 170000,
    },
    {
      _id: "21",
      image: "/images/2017 Honda Accord valve.jpg",
      type: "Expansion valve",
      make: "Honda",
      model: "Accord",
      year: "2017",
      qty: 150,
      price: 10000,
    },
    {
      _id: "22",
      image: "/images/2017 Land Rover Range Rover Evoque cabin.jpg",
      type: "Cabin filter",
      make: "Land Rover",
      model: "Range Rover Evoque",
      year: "2017",
      qty: 40,
      price: 17000,
    },
    {
      _id: "23",
      image: "/images/2017 Land Rover Range Rover Evoque comp.jpg",
      type: "Compressor",
      make: "Land Rover",
      model: "Range Rover Evoque",
      year: "2017",
      qty: 10,
      price: 350000,
    },
    {
      _id: "24",
      image: "/images/2017 Land Rover Range Rover Evoque valve.jpg",
      type: "Expansion valve",
      make: "Land Rover",
      model: "Range Rover Evoque",
      year: "2017",
      qty: 170,
      price: 14500,
    },
    {
      _id: "25",
      image: "/images/bmw 2016 x6 evap.jpg",
      type: "Exaporator",
      make: "BMW",
      model: "X6",
      year: "2016",
      qty: 15,
      price: 18000,
    },
    {
      _id: "26",
      image: "/images/bmw 2016 x6.jpg",
      type: "Condenser",
      make: "BMW",
      model: "X6",
      year: "2016",
      qty: 45,
      price: 19000,
    },
    {
      _id: "27",
      image: "/images/ford edge 2011 evap.jpg",
      type: "Evaporator",
      make: "Ford",
      model: "Edge",
      year: "2011",
      qty: 35,
      price: 13000,
    },
    {
      _id: "28",
      image: "/images/hyundai tucson 2013 evap.jpg",
      type: "Evaporator",
      make: "Hyundai",
      model: "Tucson",
      year: "2013",
      qty: 10,
      price: 19000,
    },
    {
      _id: "29",
      image: "/images/hyundai tucson 2017 cabin filter.jpg",
      type: "Cabin Filter",
      make: "Hyundai",
      model: "Tucson",
      year: "2017",
      qty: 500,
      price: 800,
    },
    {
      _id: "30",
      image: "/images/Hyundai tucson 2017 comp.jpg",
      type: "Compressor",
      make: "Hyundai",
      model: "tucson",
      year: "2017",
      qty: 10,
      price: 170000,
    },
    {
      _id: "31",
      image: "/images/hyundai tucson 2017 cabin filter.jpg",
      type: "Cabin filter",
      make: "Hyundai",
      model: "tucson",
      year: "2017",
      qty: 20,
      price: 1400,
    },
    {
      _id: "32",
      image: "/images/Hyundai tucson 2017 comp.jpg",
      type: "Compressor",
      make: "Hyundai",
      model: "tucson",
      year: "2017",
      qty: 12,
      price: 130000,
    },
    {
      _id: "33",
      image: "/images/Hyundai Tucson 2017 evap.jpg",
      type: "Evaporator",
      make: "Hyundai",
      model: "tucson",
      year: "2017",
      qty: 60,
      price: 12000,
    },
    {
      _id: "34",
      image: "/images/Hyundai Tucson 2017 valve.jpg",
      type: "Expansion valve",
      make: "Hyundai",
      model: "tucson",
      year: "2017",
      qty: 150,
      price: 11000,
    },
    {
      _id: "35",
      image: "/images/kia rio 2014 evap.jpg",
      type: "Evaporator",
      make: "Kia",
      model: "Rio",
      year: "2014",
      qty: 50,
      price: 8000,
    },
    {
      _id: "36",
      image: "/images/mazda 2012 cx7.jpg",
      type: "Condenser",
      make: "Mazda",
      model: "CX7",
      year: "2012",
      qty: 53,
      price: 16000,
    },
    {
      _id: "37",
      image: "/images/mercedes 2015 glk350 valve.jpg",
      type: "Expansion valve",
      make: "Mercedes",
      model: "GLK350",
      year: "2015",
      qty: 30,
      price: 25000,
    },
    {
      _id: "38",
      image: "/images/mercedes 2015 glk350.jpg",
      type: "Condenser",
      make: "Mercedes",
      model: "GLK350",
      year: "2015",
      qty: 31,
      price: 45000,
    },
    {
      _id: "39",
      image: "/images/mercedes glk 2015 cabin.jpg",
      type: "Cabin Filter",
      make: "Mercedes",
      model: "GLK",
      year: "2015",
      qty: 10,
      price: 35000,
    },
    {
      _id: "40",
      image: "/images/mercedes glk 2015 comp.jpg",
      type: "Compressor",
      make: "Mercedes",
      model: "GLK",
      year: "2015",
      qty: 2,
      price: 450000,
    },
    {
      _id: "41",
      image: "/images/Toyota corolla 2008.jpg",
      type: "condenser",
      make: "Toyota",
      model: "Corolla",
      year: "2008",
      qty: 30,
      price: 12000,
    },
    {
      _id: "42",
      image: "/images/Toyota highlander 2010.jpg",
      type: "condenser",
      make: "Toyota",
      model: "highlander",
      year: "2010",
      qty: 34,
      price: 12500,
    },
    {
      _id: "43",
      image: "/images/toyota venza 2016 cabin.jpg",
      type: "Cabin filter",
      make: "Toyota",
      model: "venza",
      year: "2016",
      qty: 5,
      price: 12000,
    },
    {
      _id: "44",
      image: "/images/Toyota venza 2016 comp.jpg",
      type: "Compressor",
      make: "Toyota",
      model: "venza",
      year: "2016",
      qty: 13,
      price: 2000,
    },
    {
      _id: "45",
      image: "/images/toyota venza 2016 valve.jpg",
      type: "Expansion valve",
      make: "Toyota",
      model: "venza",
      year: "2016",
      qty: 19,
      price: 20000,
    },
  ],
};
export default data;
